const express = require('express')
const router = express.Router()
const occupation = require("../controllers/occupation.controller")
router.get('/getTimetable', occupation.getTimetable)
router.get('/deleteTimetable', occupation.deleteTimetable)
router.get('/genOccupation', occupation.generateOccupation)
router.get('/occupations', occupation.getOccupationsClasse)
router.get('/occupationsEns', occupation.getOccupationsEns)
router.get('/getOEC/:id', occupation.getOccupationsEnsCompte)
router.get('/setPaied/:id', occupation.setToPaiedOccupation)
router.get('/setDone/:id', occupation.setToDoneOccupation)
router.get('/deleteOccupation/:id', occupation.deleteOccupation)
router.post('/createOccupation', occupation.createOccupation)
router.get('/occupation/:id', occupation.getOneOccupation)
router.get('/occupation', occupation.getAllOccupation)
router.get('/reinitialiser', occupation.reinitialiser)
module.exports = router

